In [1]:
#importar librerías
import pandas as pd

In [61]:
#ESTE CODIGO ES PARA HACER UN JOIN DE TODAS CABECERAS DE G1 Y G2 Y JUNTARLOS EN UN SOLA TABLA.
import os
import pandas as pd
import glob

# Carpeta donde están los archivos
carpeta = r'C:\Users\User\Desktop\Automatización'

# Buscar todos los archivos .txt en la carpeta
archivos_txt = glob.glob(os.path.join(carpeta, '*.txt'))

# Lista para guardar los DataFrames
dataframes = []

# Procesar cada archivo
for archivo in archivos_txt:
    # Leer el archivo delimitado por "|", saltando la primera fila de cabeceras en archivos posteriores
    df = pd.read_csv(archivo, delimiter='|', encoding='latin1')

    # Convertir la columna 'PAGO_LINK' a formato texto y completar con ceros a la izquierda si es necesario
    df['PAGO_LINK'] = df['PAGO_LINK'].astype(str).str.zfill(8)  # Completar con ceros para que tenga 8 dígitos
    
    # Agregar el DataFrame a la lista
    dataframes.append(df)

# Concatenar todos los DataFrames, ignorando las cabeceras duplicadas
df_concatenado = pd.concat(dataframes, ignore_index=True)

# Mostrar una vista previa del DataFrame combinado
print("Contenido de los archivos concatenados:")
print(df_concatenado.head())

print("\nArchivos concatenados exitosamente.")

Contenido de los archivos concatenados:
   FNPAGOREQ    FCNOMBRE FCAPPATERNO FCAPMATERNO     FCTEL1  FCTIPO1  \
0     838.80    INGNACIO   MELGAREJO     CAMPAÑA  943414613      NaN
1     173.41       DIANA      AGUAYO     ALVAREZ  966405233      NaN
2     616.48     EUGENIA   MARROQUIN       PINTO  959920483      NaN
3     471.10  GRIMALDINA        MORE      CHAVEZ  986207956      NaN
4     903.20      AURORA     JIMENEZ      SANTOS  927368718      NaN

        FCTEL2  FCTIPO2  FIDIASATRASOMAX         FCDNI  ...  CAMPANA_ORIGEN  \
0  948884354.0      NaN               -3     883096227  ...      Reenganche
1  966405000.0      NaN                2  440533918015  ...      Reenganche
2  945272092.0      NaN                2  547578399486  ...  Reenganche FCP
3  914470759.0      NaN                5     530753784  ...      Reenganche
4          NaN      NaN                2  722742513297  ...   Crédito Mujer

         Desc_Modulo  Desc_TipoOperacion  DIA_PAGO  PRIORIDAD  TRAMO_PROY  \
0  PRÉSTAMOS CONSUMO    Personal Mensual        10       ROJO       1.[0]
1  PRÉSTAMOS CONSUMO    Personal Mensual         5       ROJO  3.[9 A 30]
2  PRÉSTAMOS CONSUMO    Personal Mensual         5       ROJO  3.[9 A 30]
3  PRÉSTAMOS CONSUMO    Personal Mensual         0    NARANJA  3.[9 A 30]
4  PRÉSTAMOS CONSUMO    Personal Mensual         5       ROJO  3.[9 A 30]

   CUENTA_BT  FECHAPROCESO       TIPO_LISTA      FLAG_ENCARGADO
0   10041214    2024-09-07  COB_REG_CONSUMO  LISTA_REFINANSA_G1
1   10322803    2024-09-07  COB_REG_CONSUMO  LISTA_REFINANSA_G1
2    1449547    2024-09-07  COB_REG_CONSUMO  LISTA_REFINANSA_G1
3    9544191    2024-09-07  COB_REG_CONSUMO  LISTA_REFINANSA_G1
4    7958958    2024-09-07  COB_REG_CONSUMO  LISTA_REFINANSA_G1

[5 rows x 46 columns]

Archivos concatenados exitosamente.

In [41]:
df_concatenado

,FNPAGOREQ,FCNOMBRE,FCAPPATERNO,FCAPMATERNO,FCTEL1,FCTIPO1,FCTEL2,FCTIPO2,FIDIASATRASOMAX,FCDNI,...,CAMPANA_ORIGEN,Desc_Modulo,Desc_TipoOperacion,DIA_PAGO,PRIORIDAD,TRAMO_PROY,CUENTA_BT,FECHAPROCESO,TIPO_LISTA,FLAG_ENCARGADO
0,838.80,INGNACIO,MELGAREJO,CAMPAÑA,943414613,NaN,948884354.0,NaN,-3,883096227,...,Reenganche,PRÉSTAMOS CONSUMO,Personal Mensual,10,ROJO,1.[0],10041214,2024-09-07,COB_REG_CONSUMO,LISTA_REFINANSA_G1
1,173.41,DIANA,AGUAYO,ALVAREZ,966405233,NaN,966405000.0,NaN,2,440533918015,...,Reenganche,PRÉSTAMOS CONSUMO,Personal Mensual,5,ROJO,3.[9 A 30],10322803,2024-09-07,COB_REG_CONSUMO,LISTA_REFINANSA_G1
2,616.48,EUGENIA,MARROQUIN,PINTO,959920483,NaN,945272092.0,NaN,2,547578399486,...,Reenganche FCP,PRÉSTAMOS CONSUMO,Personal Mensual,5,ROJO,3.[9 A 30],1449547,2024-09-07,COB_REG_CONSUMO,LISTA_REFINANSA_G1
3,471.10,GRIMALDINA,MORE,CHAVEZ,986207956,NaN,914470759.0,NaN,5,530753784,...,Reenganche,PRÉSTAMOS CONSUMO,Personal Mensual,0,NARANJA,3.[9 A 30],9544191,2024-09-07,COB_REG_CONSUMO,LISTA_REFINANSA_G1
4,903.20,AURORA,JIMENEZ,SANTOS,927368718,NaN,NaN,NaN,2,722742513297,...,Crédito Mujer,PRÉSTAMOS CONSUMO,Personal Mensual,5,ROJO,3.[9 A 30],7958958,2024-09-07,COB_REG_CONSUMO,LISTA_REFINANSA_G1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4138,1633.23,JIMMY,PILLACA,CARRION,956308943,NaN,NaN,NaN,49,374167909263,...,SoloDNI,PRÉSTAMOS CONSUMO,Personal Mensual,20,NARANJA,5.[61 A 90],17883669,2024-09-07,COB_REG_CONSUMO,LISTA_REFINANSA_G2
4139,413.84,EFRAIN,PRADO,CAMACHO,952186424,NaN,957212556.0,NaN,12,390822966652,...,Reenganche,REFINANCIADOS,Refinanciados,25,ROJO,4.[31 A 60],8502581,2024-09-07,COB_REG_CONSUMO,LISTA_REFINANSA_G2
4140,122.30,SUSAN,BAZALAR,SARRIN,923572637,NaN,NaN,NaN,12,410277254081,...,SoloDNI,REFINANCIADOS,Refinanciados,25,ROJO,4.[31 A 60],17895424,2024-09-07,COB_REG_CONSUMO,LISTA_REFINANSA_G2
4141,646.55,NATHALY,PEÑA,RAMIREZ,938953978,NaN,942995044.0,NaN,28,615796998,...,Reenganche,PRÉSTAMOS CONSUMO,Personal Mensual,10,NARANJA,4.[31 A 60],11341636,2024-09-07,COB_REG_CONSUMO,LISTA_REFINANSA_G2
4142,1159.74,LUZ,ZAPATA,PASACHE,948039050,NaN,968630494.0,NaN,150,442705655015,...,Reenganche,PRÉSTAMOS CONSUMO,Personal Mensual,10,ROJO,8.[151 A MAS],17906563,2024-09-07,COB_REG_CONSUMO,LISTA_REFINANSA_G2

In [63]:
# Exportar el DataFrame a un archivo Excel en la carpeta indicada
ruta_salida = os.path.join(carpeta, 'datos_combinados.xlsx')
df_concatenado.to_excel(ruta_salida, index=False)  # Exportar sin el índice

print(f"Archivo exportado exitosamente en: {r'C:\Users\User\Desktop\Automatización'}")

Archivo exportado exitosamente en: C:\Users\User\Desktop\Automatización

In [67]:
import os
import pandas as pd
import glob

# Carpeta donde están los archivos
carpeta = r'C:\Users\User\Desktop\Automatización'

# Buscar todos los archivos .txt en la carpeta
archivos_txt = glob.glob(os.path.join(carpeta, '*.txt'))

# Lista para guardar los DataFrames
dataframes = []

# Procesar cada archivo
for archivo in archivos_txt:
    # Leer el archivo delimitado por "|"
    df = pd.read_csv(archivo, delimiter='|', encoding='latin1')
    
    # Convertir la columna 'PAGO_LINK' (DNI) a texto y completar con ceros a la izquierda si es necesario
    df['PAGO_LINK'] = df['PAGO_LINK'].astype(str).str.zfill(8)  # Asegurar que el DNI tenga 8 dígitos
    
    # Agregar el DataFrame a la lista
    dataframes.append(df)

# Concatenar todos los DataFrames, ignorando las cabeceras duplicadas
df_concatenado = pd.concat(dataframes, ignore_index=True)

# Seleccionar las columnas que necesitamos: DNI (PAGO_LINK) y los teléfonos
df_telefonos = df_concatenado[['PAGO_LINK', 'FCTEL1', 'FCTEL2', 'FCTEL3', 'FCTEL4', 'FCTEL5']]

# Unpivot los teléfonos para que estén en una sola columna
df_telefonos_melted = df_telefonos.melt(id_vars='PAGO_LINK', value_vars=['FCTEL1', 'FCTEL2', 'FCTEL3', 'FCTEL4', 'FCTEL5'],
                                        var_name='Tipo_Telefono', value_name='Teléfono')

# Eliminar filas donde el teléfono sea NaN
df_telefonos_melted = df_telefonos_melted.dropna(subset=['Teléfono'])

# Convertir los teléfonos a enteros para eliminar el .0, y luego a texto para que se guarden bien en Excel
df_telefonos_melted['Teléfono'] = df_telefonos_melted['Teléfono'].astype(int).astype(str)

# Filtrar y eliminar los teléfonos que no comienzan con "9" o que sean "999999999"
df_telefonos_melted = df_telefonos_melted[df_telefonos_melted['Teléfono'].str.startswith('9')]
df_telefonos_melted = df_telefonos_melted[df_telefonos_melted['Teléfono'] != '999999999']

# Eliminar la columna 'Tipo_Telefono' que no es necesaria
df_final = df_telefonos_melted[['PAGO_LINK', 'Teléfono']]

# Crear la columna "Concatenado" con el formato DNI-TELEFONO
df_final['Concatenado'] = df_final['PAGO_LINK'] + '-' + df_final['Teléfono']

# Ordenar los DNI de menor a mayor
df_final = df_final.sort_values(by='PAGO_LINK')

# Exportar el DataFrame agrupado a un archivo Excel en la carpeta indicada
ruta_salida = os.path.join(carpeta, 'dni_telefonos_concatenados.xlsx')
df_final.to_excel(ruta_salida, index=False)  # Exportar sin el índice

print(f"Archivo exportado exitosamente en: {ruta_salida}")

Archivo exportado exitosamente en: C:\Users\User\Desktop\Automatización\dni_telefonos_concatenados.xlsx